# Generated by Django 3.0.2 on 2020-01-22 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AttendApp', '0007_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='shift',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='AttendApp.Shift'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
